#!/bin/bash
set -e # Exit on any error

aws configure set aws_access_key_id $AWS_ACCESS_KEY
aws configure set aws_secret_access_key $AWS_SECRET_KEY
aws configure set region us-east-1

aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws

docker build -t public.ecr.aws/g8w4z0q4/circleci-base:"$CIRCLE_BRANCH" .
docker push public.ecr.aws/g8w4z0q4/circleci-base:"$CIRCLE_BRANCH"
